### ISSUE TITLE
About the file format.

### ISSUE THREAD

**Issue by jwchen119** [0015/7-Color-E-Paper-Digital-Photo-Frame#1]
Hi Eric,

First of all, thanks for sharing this project, this really inspired me the posibility of digital photo frame by the long battery life.
However, I would like to understand why we don't send a .bmp file from the server to the ESP32, especially since its file size is much smaller than a hex file?
I'm asking because I'm using the ESP32C6 as the MCU, which cannot have external PSRAM and has only 4MB of RAM. I'm unsure if I can use the built-in flash to temporarily store .bmp files before sending them to the ePaper display.

**Comment by 0015** [comment]
@jwchen119 In order to draw on the screen, the contents of the file must be stored in memory. In that case, I thought it would be more efficient to store it in memory from the local server from the beginning, so I made it like this. I think it would be good to work in the way you want. 
If there is no PSRAM, I think it's okay to use malloc() instead of ps_malloc(). Also, if you refer to _Test_E_Paper_5_56inch_7color, you can see that it draws using the image of the .h file.

**Comment by jwchen119** [comment]
Hi Eric,

I'm using firebeetle 2 ESP32-C6, so I have to correct the spec of it, the SRAM is only 512KB.
But the the spec shows 4MB of flash, not sure the size is enough to store the hex files and I might have to use spiffs to store the files.
I've brought Waveshare Spectra 6 7.3" ePaper for the display. Not sure if the usage is the same as yours.

**Comment by 0015** [comment]
@jwchen119 It seems like the easiest way would be to include the .h file inside and read the image locally. Or if you need to allocate it dynamically, you'll probably have to modify your code to download the file to a SPIFFS partition and then read from that file. The Waveshare Spectra 6 7.3" ePaper looks like a different model than the one I used. Check out the SPI commands.
